require "creamerscript/substitutor"
require "creamerscript/compiler"
require "creamerscript/transformers/method_definition"
require "creamerscript/transformers/method_invocation"
require "creamerscript/transformers/property_invocation"
